name: CI
env:
  FILE_NAME: hello-server
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * 1-6'
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Build GO LinuxLastVersion
        run: go build ${{env.FILE_NAME}}.go
        
      - name: Build GO WindowsLastVersion
        run: GOOS=windows GOARCH=amd64 go build ${{env.FILE_NAME}}.go

      - name: Upload artifact for linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}
            
      - name: Upload artifact for windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe
  download-and-run-linux:
    name: Download and run Linux
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download a Build Artifact Linux
        uses: actions/download-artifact@v4.1.8
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}
      - name: Script run.sh
        run: cat ./run.sh
        
